version: '3'

services:
  mongodb:
    image: mongo:8.0.3
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  mongo-express:
    image: mongo-express:1.0.2-18
    restart: on-failure
    hostname: mongo-express
    ports:
      - 80:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_OPTIONS_EDITORTHEME=darcula
      - ME_CONFIG_BASICAUTH_USERNAME=estatcamp
      - ME_CONFIG_BASICAUTH_PASSWORD=estatcamp
    depends_on:
      mongodb:
        condition: service_healthy

  mongolite:
    build: .
    command: R -e "devtools::test()"
    restart: on-failure
    container_name: mongolite
    depends_on:
      mongodb:
        condition: service_healthy